### PR TITLE
Shutdown non gracefully if graceful shutdown fails

### PR DESCRIPTION
**Pull request by aquamatthias**

### CODE REVIEW

**Review by markus1189 — APPROVED** [review]
We currently force the shutdown of the `kclWorker` outside of reactive-kinesis, so :+1: from me

**Comment by markus1189** [comment]
Something that surprised me: in JFrog, there are already `0.7.2` - `0.7.5` versions of reactive kinesis:

https://moiadev.jfrog.io/moiadev/webapp/#/artifacts/browse/tree/General/sbt-release/io/moia/com/weightwatchers/reactive-kinesis_2.12/0.7.2

Created in 2017?  We either have to delete them or bump the version...

**Comment by aquamatthias** [comment]
@markus1189 Thanks for the hint. I think deleting in artifactory is not possible (at least for me). So I would suggest to bump the version.

**Comment by markus1189** [comment]
Bumping is fine for me

**Comment by aquamatthias** [comment]
Published as 0.7.6

**Pull request merged**
